import { describe, test, expect } from "bun:test";
import { commentHeader, stripVolatile } from "../src/generation-meta.js";

describe("commentHeader", () => {
  test("produces the // block with Build/Generated/Run lines (secondsee-compatible shape)", () => {
    const h = commentHeader({ runCommand: "bun run generate:swift", by: "@ebowwa/node-codegen" });
    expect(h.startsWith("//\n// AUTO-GENERATED by @ebowwa/node-codegen — do not edit manually.\n")).toBe(true);
    expect(h).toMatch(/\/\/ Build: \S+\+\S+\n/); // <version>+<sha>
    expect(h).toMatch(/\/\/ Generated: \S+\n/);
    expect(h).toMatch(/\/\/ Run: bun run generate:swift\n/);
    expect(h.endsWith("\n\n")).toBe(true); // trailing blank line
  });

  test("includes a Source line only when source is given", () => {
    expect(commentHeader({ runCommand: "x" })).not.toMatch(/Source:/);
    expect(commentHeader({ runCommand: "x", source: "node-defs.ts" })).toMatch(/\/\/ Source: node-defs.ts\n/);
  });

  test("honors a custom comment prefix", () => {
    expect(commentHeader({ runCommand: "x", prefix: "#" }).startsWith("#\n# AUTO-GENERATED")).toBe(true);
  });
});

describe("stripVolatile (case-insensitive)", () => {
  test("strips JSON object form", () => {
    expect(stripVolatile('{"build": "0.2.0+abc", "generated": "2026-01-01T00:00:00Z"}')).toBe(
      '{"build": "<STRIPPED>", "generated": "<STRIPPED>"}',
    );
  });
  test("strips comment form in BOTH cases", () => {
    const swift = "// Build: 0.2.0+abc\n// Generated: 2026-01-01\n// lower: build: x generated: y";
    const out = stripVolatile(swift);
    expect(out).not.toContain("0.2.0+abc");
    expect(out).not.toContain("2026-01-01");
    expect(out).not.toContain(": x\n");
    expect(out).toContain("build: <STRIPPED>");
  });
});
