import { describe, test, expect } from "bun:test";
import { commentHeader, jsdocHeader, stripVolatile } from "../src/generation-meta.js";

/** Mask the volatile Build/Generated values so the byte SHAPE can be compared exactly. */
const norm = (s: string) => s.replace(/Build: \S+/g, "Build: X").replace(/Generated: \S+/g, "Generated: X");

describe("commentHeader (// style — byte-matches secondsee swift/kotlin)", () => {
  test("exact shape with closing // + trailing blank line", () => {
    const h = commentHeader({ runCommand: "bun run generate:swift", by: "@ebowwa/node-codegen" });
    expect(norm(h)).toBe(
      "//\n// AUTO-GENERATED by @ebowwa/node-codegen — do not edit manually.\n" +
        "// Build: X\n// Generated: X\n// Run: bun run generate:swift\n//\n\n",
    );
  });

  test("source line only when source given", () => {
    expect(commentHeader({ runCommand: "x" })).not.toMatch(/Source:/);
    expect(commentHeader({ runCommand: "x", source: "node-defs.ts" })).toMatch(/\/\/ Source: node-defs.ts/);
  });

  test("custom comment prefix", () => {
    expect(commentHeader({ runCommand: "x", prefix: "#" }).startsWith("#\n# AUTO-GENERATED")).toBe(true);
  });
});

describe("jsdocHeader (/** */ style — byte-matches secondsee ts)", () => {
  test("exact shape with source", () => {
    const h = jsdocHeader({ runCommand: "bun run x", by: "@ebowwa/node-codegen", source: "node-defs.ts" });
    expect(norm(h)).toBe(
      "/**\n * AUTO-GENERATED by @ebowwa/node-codegen — do not edit manually.\n" +
        " * Build: X\n * Generated: X\n * Source: node-defs.ts\n *\n * To regenerate: bun run x\n */\n\n",
    );
  });

  test("omits Source when not given", () => {
    const h = jsdocHeader({ runCommand: "x" });
    expect(h).not.toContain("Source:");
    expect(h.startsWith("/**\n * AUTO-GENERATED")).toBe(true);
    expect(h.endsWith(" */\n\n")).toBe(true);
  });
});

describe("stripVolatile (case-insensitive)", () => {
  test("strips JSON object form", () => {
    expect(stripVolatile('{"build": "0.2.0+abc", "generated": "2026-01-01T00:00:00Z"}')).toBe(
      '{"build": "<STRIPPED>", "generated": "<STRIPPED>"}',
    );
  });
  test("strips comment form in BOTH cases", () => {
    const out = stripVolatile("// Build: 0.2.0+abc\n// Generated: 2026-01-01");
    expect(out).not.toContain("0.2.0+abc");
    expect(out).not.toContain("2026-01-01");
    expect(out).toContain("build: <STRIPPED>");
  });
});
