// @ebowwa/codegen-kit — generation provenance + drift stripping.
// Consumer-agnostic: reads the CONSUMER's package.json from process.cwd() so the
// build stamp reflects whichever repo is generating, not this kit.

import { readFileSync } from "node:fs";
import { execSync } from "node:child_process";

function readCwdVersion(): string {
  try {
    const pkg = JSON.parse(readFileSync(new URL("package.json", `file://${process.cwd()}/`), "utf-8"));
    return (pkg?.version as string | undefined) ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

export function gitShortSha(): string {
  try {
    return execSync("git rev-parse --short=7 HEAD", { encoding: "utf-8" }).trim();
  } catch {
    return "unknown";
  }
}

/** ISO 8601 timestamp captured at module load. Volatile — stripped before --check diffs. */
export const generationTimestamp: string = new Date().toISOString();

/** `<consumerVersion>+<git-sha>`. Volatile. */
export function buildNumber(): string {
  return `${readCwdVersion()}+${gitShortSha()}`;
}

export interface AutogenMeta {
  readonly notice: string;
  readonly build: string;
  readonly generated: string;
  readonly source?: string;
  readonly regenerate: string;
}

/** Provenance object to embed as `_autogen` in a generated JSON artifact. */
export function autogenMeta(runCommand: string, source?: string): AutogenMeta {
  return {
    notice: "AUTO-GENERATED — do not edit manually.",
    build: buildNumber(),
    generated: generationTimestamp,
    source,
    regenerate: runCommand,
  };
}

/** A line-comment autogen header (default `//`), byte-compatible with
 *  secondsee/node-codegen's swiftAutogenHeader / kotlinAutogenHeader when
 *  by = "@ebowwa/node-codegen". Includes a closing comment line + blank line. */
export function commentHeader(opts: {
  runCommand: string;
  by?: string;
  source?: string;
  prefix?: string;
}): string {
  const prefix = opts.prefix ?? "//";
  const by = opts.by ?? "codegen";
  const lines = [
    prefix,
    `${prefix} AUTO-GENERATED by ${by} — do not edit manually.`,
    `${prefix} Build: ${buildNumber()}`,
    `${prefix} Generated: ${generationTimestamp}`,
    ...(opts.source ? [`${prefix} Source: ${opts.source}`] : []),
    `${prefix} Run: ${opts.runCommand}`,
    prefix,
    "",
  ];
  return lines.join("\n") + "\n";
}

/** A JSDoc block-comment autogen header (`/** … *\/`), byte-compatible with
 *  secondsee/node-codegen's tsAutogenHeader when by = "@ebowwa/node-codegen". */
export function jsdocHeader(opts: { runCommand: string; by?: string; source?: string }): string {
  const by = opts.by ?? "codegen";
  const lines = [
    "/**",
    ` * AUTO-GENERATED by ${by} — do not edit manually.`,
    ` * Build: ${buildNumber()}`,
    ` * Generated: ${generationTimestamp}`,
    ...(opts.source ? [` * Source: ${opts.source}`] : []),
    " *",
    ` * To regenerate: ${opts.runCommand}`,
    " */",
    "",
  ];
  return lines.join("\n") + "\n";
}


/** Strip volatile provenance tokens before diffing, across JSON and comment formats.
 *  Case-insensitive — handles `"build"`/`"generated"` (JSON) and `Build:`/`Generated:`
 *  / `build:`/`generated:` (comments, any case). */
export function stripVolatile(s: string): string {
  return s
    .replace(/"generated":\s*"[^"]*"/gi, '"generated": "<STRIPPED>"')
    .replace(/"build":\s*"[^"]*"/gi, '"build": "<STRIPPED>"')
    .replace(/\bgenerated:\s*\S+/gi, "generated: <STRIPPED>")
    .replace(/\bbuild:\s*\S+/gi, "build: <STRIPPED>");
}

